import Card from '@/components/Card';
import InputSearch from '@/components/InputSearch';
import Head from 'next/head';
import * as S from './styles';
import { api } from '@/services/api';
import { ICharacter } from '@/types/characters';
import { useQuery } from '@tanstack/react-query';


function CharacterListScreen() {

  const {data: characters} = useQuery({queryKey: ['todos'], queryFn: api.getCharacters});

  return (
    <>
      <Head>
        <title>Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Container>
        <S.Header>
          <InputSearch />
        </S.Header>

        <S.CardContainer>
          {characters?.results.map((character: ICharacter) => (
            <Card key={character.id} character={character}/>
          ))}
        </S.CardContainer>
      </S.Container>
    </>
  );
}

export default CharacterListScreen;
