import InputSearch from '@/components/InputSearch';
import Head from 'next/head';

import * as S from './styles';

function CharacterListScreen() {
  return (
    <>
      <Head>
        <title>Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Container>
        <InputSearch />
        <S.Header>
          <strong>10 characters</strong>
        </S.Header>
      </S.Container>
    </>
  );
}

export default CharacterListScreen;
