import { useEffect, useState } from 'react';
import Card from '@/components/Card';
import InputSearch from '@/components/InputSearch';
import Image from 'next/image';
import Head from 'next/head';
import * as S from './styles';
import { api } from '@/services/api';
import { ICharacter } from '@/types/characters';

function CharacterListScreen() {
  const [charactersList, setCharactersList] = useState<ICharacter[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isError, setIsError] = useState(false);

  useEffect(() => {
    fetchCharacters();
  }, []);

  async function fetchCharacters() {
    const response = await api.getCharacters();
    const characters = response.results;
    setCharactersList(characters);

  }

  return (
    <>
      <Head>
        <title>Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Container>
        <InputSearch />
        <S.Header>
          <strong>{charactersList.length} characters</strong>
        </S.Header>

        <S.CardContainer>
          {charactersList.map((character) => (
            <Card key={character.id}>
              <S.ImageContainer>
                <Image
                  src={character.image}
                  alt="Picture of the author"
                  width={400}
                  height={400}
                />
              </S.ImageContainer>
              <S.InfoContainer>
                <S.InfoBox>
                  <S.Info>
                    <strong> Name: </strong>
                    <label>{character.name}</label>
                  </S.Info>
                  <S.Info>
                    <strong> Status: </strong>
                    <label>{character.status}</label>
                  </S.Info>
                  <S.Info>
                    <strong>Specie: </strong>
                    {character.species}
                  </S.Info>
                  <S.Info>
                    <strong> Type: </strong>
                    {character.type ? character.type : 'No type'}
                  </S.Info>
                  <S.Info>
                    <strong> Origin: </strong>
                    {character.species}
                  </S.Info>
                  <S.Info>
                    <strong> Gender: </strong>
                    {character.gender}
                  </S.Info>
                </S.InfoBox>
              </S.InfoContainer>
            </Card>
          ))}
        </S.CardContainer>
      </S.Container>
    </>
  );
}

export default CharacterListScreen;
